mysite/accounts/urls.py
from django.urls import path

from . import views

# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'accounts'

urlpatterns = [
    # ex: /accounts/signup/
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('profile/', views.profile, name='profile'),
]

mysite/chat/urls.py
from django.conf.urls import url

from . import views


app_name = 'chat'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create_user/$', views.create_user, name='create_user'),
    url(r'^room/$', views.room, name='room'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'chat/', include('chat.urls', namespace='chat')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

mysite/accounts/models.py
from django.db import models

# Create your models here.

mysite/chat/models.py
import google.oauth2.credentials
import requests

from django.conf import settings
from django.forms.models import model_to_dict
from django.db import models


class Credentials(models.Model):
    token = models.CharField(max_length=255)
    refresh_token = models.CharField(max_length=255, blank=True)
    token_uri = models.CharField(max_length=255)
    client_id = models.CharField(max_length=255)
    client_secret = models.CharField(max_length=255)
    scopes = models.CharField(max_length=255)
    avatar = models.CharField(max_length=255, null=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.user

    def to_dict(self):
        return model_to_dict(self, exclude=('id', 'user'))

    @property
    def auth(self):
        if not hasattr(self, '_auth'):
            self._auth = google.oauth2.credentials.Credentials(**self.to_dict())
        return self._auth

    def revoke(self):
        requests.post(
            'https://accounts.google.com/o/oauth2/revoke',
            params={'token': self.auth.token},
            headers={'content-type': 'application/x-www-form-urlencoded'}
        )
        self.delete()


class Profile(models.Model):
    avatar = models.CharField(max_length=255)
    user_name = models.CharField(max_length=255)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

mysite/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import render
from oauthlib.oauth2 import MissingCodeError
from django.conf import settings
import google_auth_oauthlib


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'


def profile(request):
    return render(request, 'chat/index.html', {})

mysite/chat/views.py
from django.shortcuts import render, redirect
from django.utils.safestring import mark_safe
import json
from django.contrib.auth.decorators import login_required


@login_required
def index(request):
    return render(request, 'chat/index.html', {})
    # TODO: arrange login form of google


@login_required
def create_user(request):
    request.session.create()
    request.session['user_name'] = request.user.profile.user_name
    request.session['room_name'] = request.POST.get(key='room_name')
    request.session['icon_url'] = request.user.profile.avatar
    return redirect('chat:room')
    # TODO: arrange form to enter room


@login_required
def room(request):
    key = request.session.session_key or None
    if key:
        room_name = request.session['room_name']
        key = mark_safe(json.dumps(key))
        return render(request, 'chat/room.html', {
            'room_name_json': mark_safe(json.dumps(room_name)),
            'session_key': key,
        })
    else:
        return render(request, 'chat/index.html', {})

# def test(request):
#    return render(request, 'chat/test.html', {})


# @login_required
# def auth(request):
#    print('aaa')
#    print(request.user)
#    print(type(request.user))
#    if hasattr(request.user, 'credentials'):
#        print('aaa')
#        return render(request, 'chat/index.html', {})
#
#    flow = google_auth_oauthlib.flow.Flow.from_client_secrets_file(
#        settings.CLIENT_SECRET, settings.SCOPES
#    )
#    flow.redirect_uri = settings.REDIRECT_URI
#    authorization_url, state = flow.authorization_url(
#        approval_prompt='force',
#        access_type='offline',
#        include_granted_scopes='true'
#    )
#    request.session['state'] = state
#    print(authorization_url)
#    return redirect(authorization_url)
#
#
# @login_required
# def callback(request):
#    if hasattr(request.user, 'credentials'):
#        return render(request, 'chat/index.html', {})
#
#    print(type(request.user))
#    print(request.user)
#    state = request.session['state']
#    flow = google_auth_oauthlib.flow.Flow.from_client_secrets_file(
#        settings.CLIENT_SECRET, settings.SCOPES, state=state
#    )
#    flow.redirect_uri = settings.REDIRECT_URI
#    authorization_response = request.build_absolute_uri()
#    try:
#        flow.fetch_token(authorization_response=authorization_response)
#    except MissingCodeError:
#        pass
#    else:
#        print(request.user + ' unko')
#        Credentials.objects.create(
#            token=flow.credentials.token,
#            refresh_token=flow.credentials.refresh_token or '',
#            token_uri=flow.credentials.token_uri,
#            client_id=flow.credentials.client_id,
#            client_secret=flow.credentials.client_secret,
#            scopes=flow.credentials.scopes,
#            user=request.user
#        )
#    return render(request, 'chat/room.html', {})

mysite/accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

mysite/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h1>Sign up</h1>
<section class="common-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="submit">Sign up</button>
    </form>
</section>
{% endblock %}

mysite/chat/templates/chat/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
    <link rel="stylesheet" type="text/css" href="{% static 'chat/css/index.css' %}">
</head>
<body>
<div id="form-main">
  <div id="form-div">
    <form class="form" action="{% url 'chat:create_user' %}" method="post">
        {% csrf_token %}
      <p class="user_name">
        <input name="user_name" type="text" class="validate[required,custom[onlyLetter],length[0,100]] feedback-input" placeholder="User" id="user_name" />
      </p>
      <p class="room_name">
        <input name="room_name" type="text" class="validate[required,custom[email]] feedback-input" id="room_name" placeholder="Room" />
      </p>
      <div class="submit">
        <input type="submit" value="JOIN CHAT" id="button-blue"/>
        <div class="ease"></div>
      </div>
    </form>
  </div>
</div>
    <script>
        document.querySelector('#name').focus();
        document.querySelector('#name').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#button-blue').click();
            }
        };

        document.querySelector('#button-blue').onclick = function(e) {
            var roomName = document.querySelector('#email').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

mysite/chat/templates/chat/room.html
<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset="utf-8"/>
    <title>Chat Room</title>
    <link rel="stylesheet" type="text/css" href="{% static 'chat/css/style.css' %}">
</head>
<body>
    <div class="line-bc">
        <div class="line-chat" id="chat">
            <div id="line">
            </div>
        </div>
        <div class="line-input">
            <tr>
            <td>
                <label for="image">
                +
                <input id="image" name="image" type="file" accept="image/*" style="display: none;">
                </label>
            </td>
            <td><input id="chat-message-input" size="50" type="text" class="box2"/></td>
            <td><input id="chat-message-submit" type="button" value="Send" class="square_btn"/></td>
            </tr>
        </div>
    </div>
</body>
<script>
    var roomName = {{ room_name_json }};
    var session_key = {{ session_key }};

    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/chat/' + roomName + '/');
    var keyDownCode = 0;

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var type = data['type'];
        var key = data['session_key'];
        var time = data['time'];
        var message;
        var url;
        var div_element = document.createElement('div');
        var chatting_element = document.createElement('div');
        var says_element = document.createElement('div');
        var user_name_element = document.createElement('div');
        var p_element = document.createElement('p');
        var face_icon_div_element = document.createElement('div');
        var face_icon_img_element = document.createElement('img');
        var img_element = document.createElement('img');
        var self_img_element = document.createElement('img');
        var time_element = document.createElement('div');
        time_element.textContent = time;
        if(key !== session_key) {
            div_element.className = 'balloon6';
            chatting_element.className = 'chatting';
            says_element.className = 'says';
            user_name_element.className = 'user_name';
            face_icon_div_element.className = 'faceicon';
            face_icon_img_element.src = data['icon_url'];
            time_element.className = 'chat_time';
            if(type === 'chat_message'){
                message = data['message'];
                says_element.innerText = message;
            }else if(type === 'chat_image'){
                url = data['url'];
                img_element.src = url;
                img_element.width = 300;
                says_element.appendChild(img_element);
            }
            user_name_element.textContent=data['user_name'];
            chatting_element.appendChild(user_name_element);
            chatting_element.appendChild(says_element);
            chatting_element.appendChild(time_element);
            face_icon_div_element.appendChild(face_icon_img_element);
            div_element.appendChild(face_icon_div_element);
            div_element.appendChild(chatting_element);
        }else {
            div_element.className = 'mycomment';
            time_element.className = 'mycomment_time';
            if(type === 'chat_message'){
                message = data['message'];
                p_element.innerText =  message ;
            }else if(type === 'chat_image'){
                url = data['url'];
                self_img_element.src = url;
                self_img_element.width = 300;
                p_element.appendChild(self_img_element);
            }
            div_element.appendChild(p_element);
            div_element.appendChild(time_element);
        }
        var parent_object = document.getElementById('line');
        parent_object.appendChild(div_element);
        var scroll_obj = document.getElementById('chat');
        scroll_obj.scrollTop = scroll_obj.scrollHeight;
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeydown = function(e){
        keyDownCode = e.which;
    }
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.which === 13 && keyDownCode == e.which) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        message.replace('&nbsp;', ' ');
        if(message) {
            chatSocket.send(JSON.stringify({
                'message': message,
                'session_key': session_key,
            }));
            messageInputDom.value = '';
        }
    };

    document.getElementById('image')
        .addEventListener('change', function(evt) {
            var file = evt.target.files[0];
            var input = document.querySelector('#image');
            chatSocket.send(file);
            input.value = '';

        }, false);

</script>
</html>

mysite/chat/templates/chat/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if user.credentials %}
<p>認証完了</p>
{% else %}
<p>認証未完了</p>
<a href="{% url 'chat:auth' %}">認証</a>
{% endif %}
{% if user %}
<p>ユーザはある</p>
{% endif %}
</body>
</html>

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>